# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64)),
                ('qid', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'aliases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communes',
            fields=[
                ('qid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('wp_title', models.CharField(max_length=255)),
                ('wv_title', models.CharField(max_length=255)),
                ('commons_category', models.CharField(max_length=255)),
                ('suggest_str', models.CharField(max_length=255)),
                ('insee', models.CharField(max_length=16)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=64, null=True)),
                ('progress', models.CharField(blank=True, max_length=20, null=True)),
                ('importance', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geoshape', models.TextField()),
                ('section_geography', models.IntegerField()),
                ('section_history', models.IntegerField()),
                ('section_economy', models.IntegerField()),
                ('section_demographics', models.IntegerField()),
                ('section_etymology', models.IntegerField()),
                ('section_governance', models.IntegerField()),
                ('section_culture', models.IntegerField()),
                ('section_infrastructure', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'communes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('size', models.IntegerField()),
                ('has_sub_article', models.IntegerField()),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=64)),
                ('mean_size', models.IntegerField()),
                ('importance', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section_stats',
                'managed': False,
            },
        ),
    ]
