# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='communes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionstats',
            options={},
        ),
    ]
