# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geoloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geoshape', models.TextField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='communes',
            name='mc_frontend_latitud_97cb86_idx',
        ),
        migrations.RemoveField(
            model_name='communes',
            name='geoshape',
        ),
        migrations.RemoveField(
            model_name='communes',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='communes',
            name='longitude',
        ),
        migrations.AddField(
            model_name='geoloc',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_frontend.Communes'),
        ),
        migrations.AddIndex(
            model_name='geoloc',
            index=models.Index(fields=['latitude', 'longitude'], name='mc_frontend_latitud_2411cf_idx'),
        ),
    ]
