# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_frontend', '0002_auto_20170616_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communes',
            name='badge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='communes',
            index=models.Index(fields=['suggest_str'], name='communes_suggest_114181_idx'),
        ),        
        migrations.AddIndex(
            model_name='communes',
            index=models.Index(fields=['qid'], name='communes_qid_cdfd5e_idx'),
        ),
    ]
