# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_frontend', '0003_auto_20170620_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geoshape',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='geoloc',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='geoloc',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
