SECTIONS_LOOKUP_TABLE = {
    "section_geography":
        ["Géographie",
         "Lieux et monuments",
         "Monuments",
         "Jumelages",
         "Environnement",
         "Édifice religieux",
         "Communes limitrophes",
         "Édifices religieux",
         "Lieux-dits et écarts",
         "Climat",
         "Vignoble",
         "Lieux, monuments et pôles d'intérêt",
         "Sites et monuments",
         "Patrimoine naturel",
         "Monuments et sites",
         "Monuments et lieux touristiques",
         "Géologie",
         "Hydrographie",
         "Lieux-dits"],
    "section_history":
        ["Histoire",
         "Héraldique",
         "Blasonnement",
         "Emblèmes",
         "Armoiries",
         "Archives",
         "Blason",
         "Historique"],
    "section_economy":
        ["Économie",
         "Tourisme",
         "Économie et tourisme",
         "Activités économiques",
         "Activité économique"],
    "section_demographics":
        ["Population et société",
         "Personnalités liées à la commune",
         "Démographie",
         "Enseignement",
         "Personnalités liées",
         "Personnalités",
         "Personnalité liée à la commune",
         "Cultes",
         "Culte",
         "Éducation"],
    "section_etymology":
        ["Toponymie",
         "Toponyme",
         "Toponymie et héraldique",
         "Toponymie et hydronymie",
         "Dénomination",
         "Étymologie",
         "Nom des habitants"],
    "section_governance":
        ["Politique et administration",
         "Administration",
         "Santé",
         "Jumelage",
         "Intercommunalité"],
    "section_culture":
        ["Culture locale et patrimoine",
         "Culture et patrimoine",
         "Activité et manifestations",
         "Vie locale",
         "Sports",
         "Équipements",
         "Équipements, services et vie locale",
         "Culture",
         "Événements",
         "Patrimoine",
         "Vie pratique",
         "Équipements et services",
         "Langue bretonne",
         "Patrimoine religieux",
         "Associations",
         "Manifestations",
         "Équipements ou services",
         "Activités festives",
         "Activité culturelle et manifestations",
         "Loisirs",
         "Activité, label et manifestations",
         "Vie associative",
         "Cadre de vie",
         "Cinéma",
         "Activités",
         "Activités et manifestations",
         "Gastronomie",
         "Manifestations culturelles et festivités",
         "Festivités",
         "Sport",
         "Patrimoine civil",
         "Distinctions culturelles",
         "Animations",
         "Infrastructures",
         "Fêtes et loisirs",
         "Société",
         "Vie culturelle",
         "Littérature",
         "Activités associatives, culturelles, festives et sportives"],
    "section_infrastructure":
        ["Urbanisme",
         "Transports",
         "Transport",
         "Voies de communication et transports",
         "Transports et voies de communications",
         "Urbanisme et habitat",
         "Transports en commun",
         "Urbanisation",
         "Industrie"],
}

SECTIONS_NAMES = list(SECTIONS_LOOKUP_TABLE.keys())

FILE_BLACKLIST = [
    "Balise_GR.png",
    "Cotes-dArmor_department_relief_location_map.jpg",
    "Crystal_Clear_action_half_lock.png",
    "Crystal_Clear_action_lock5.png",
    "Finances_locales_logo.png",
    "France_relief_location_map.jpg",
    "Isère_department_relief_location_map.jpeg",
    "Locator_Dot.png",
    "Logo-Mairie.png",
    "Magnify-clip.png",
    "Portail_Pays_basque_2.png",
    "Pyrénées-Atlantiques_department_relief_location_map.jpg",
]

IMPORTANCES = [
    "maximum",
    "élevée",
    "moyenne",
    "faible",
    "?",
]
